error: calls to `push` immediately after creation
  --> $DIR/vec_init_then_push.rs:5:5
   |
LL | /     let mut def_err: Vec<u32> = Default::default();
LL | |     def_err.push(0);
   | |____________________^ help: consider using the `vec![]` macro: `let mut def_err: Vec<u32> = vec![..];`
   |
   = note: `-D clippy::vec-init-then-push` implied by `-D warnings`

error: calls to `push` immediately after creation
  --> $DIR/vec_init_then_push.rs:8:5
   |
LL | /     let mut new_err = Vec::<u32>::new();
LL | |     new_err.push(1);
   | |____________________^ help: consider using the `vec![]` macro: `let mut new_err = vec![..];`

error: calls to `push` immediately after creation
  --> $DIR/vec_init_then_push.rs:11:5
   |
LL | /     let mut cap_err = Vec::with_capacity(2);
LL | |     cap_err.push(0);
LL | |     cap_err.push(1);
LL | |     cap_err.push(2);
   | |____________________^ help: consider using the `vec![]` macro: `let mut cap_err = vec![..];`

error: calls to `push` immediately after creation
  --> $DIR/vec_init_then_push.rs:23:5
   |
LL | /     new_err = Vec::new();
LL | |     new_err.push(0);
   | |____________________^ help: consider using the `vec![]` macro: `new_err = vec![..];`

error: aborting due to 4 previous errors

